name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 6' # https://crontab.guru/#0_0_*_*_6

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./bin"
